// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Automate.Salesforce.Persistence;

#nullable disable

namespace Umbraco.Automate.Salesforce.Persistence.Sqlite.Migrations
{
    [DbContext(typeof(SalesforceDbContext))]
    partial class SalesforceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("Umbraco.Automate.Salesforce.Persistence.SalesforcePollingStateEntity", b =>
                {
                    b.Property<Guid>("AutomationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPollUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("TEXT");

                    b.HasKey("AutomationId");

                    b.ToTable("umbracoAutomateSalesforcePollingState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
