// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Umbraco.Automate.Salesforce.Persistence;

#nullable disable

namespace Umbraco.Automate.Salesforce.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(SalesforceDbContext))]
    partial class SalesforceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Umbraco.Automate.Salesforce.Persistence.SalesforcePollingStateEntity", b =>
                {
                    b.Property<Guid>("AutomationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastPollUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("SnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AutomationId");

                    b.ToTable("umbracoAutomateSalesforcePollingState", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
